(() => {
  const card = document.getElementById("scratchCard");
  const canvas = document.getElementById("scratchCanvas");
  const countdown = document.getElementById("countdown");
  const particleCanvas = document.getElementById("particleCanvas");
  if (!card || !canvas || !countdown || !particleCanvas) return;
  const context = canvas.getContext("2d", { willReadFrequently: true });
  const particleContext = particleCanvas.getContext("2d");
  const reducedMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;
  const targetDate = new Date("2026-12-19T00:00:00+05:30");
  const progressBar = document.getElementById("scratchProgressBar");
  const status = document.getElementById("scratchStatus");
  let scratching = false; let finished = false; let lastPoint = null; let countdownTimer = null; let lastVibration = 0;
  let scratchWidth = 0; let scratchHeight = 0; let particleWidth = 0; let particleHeight = 0; let particles = []; let particleFrame = null; let particleActive = false;
  function sizeScratchCanvas() { const bounds = card.getBoundingClientRect(); const density = Math.min(devicePixelRatio || 1, 2); scratchWidth = bounds.width; scratchHeight = bounds.height; canvas.width = scratchWidth * density; canvas.height = scratchHeight * density; canvas.style.width = `${scratchWidth}px`; canvas.style.height = `${scratchHeight}px`; context.setTransform(density, 0, 0, density, 0, 0); context.globalCompositeOperation = "source-over"; const gradient = context.createLinearGradient(0, 0, scratchWidth, scratchHeight); gradient.addColorStop(0, "#72522d"); gradient.addColorStop(.5, "#c9aa6b"); gradient.addColorStop(1, "#80603a"); context.fillStyle = gradient; context.fillRect(0, 0, scratchWidth, scratchHeight); context.fillStyle = "rgba(255,255,255,.1)"; for (let index = 0; index < 600; index += 1) context.fillRect(Math.random() * scratchWidth, Math.random() * scratchHeight, 1, 1); }
  function point(event) { const bounds = canvas.getBoundingClientRect(); return { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; }
  function updateProgress() { const sample = 70; const sampleCanvas = document.createElement("canvas"); sampleCanvas.width = sample; sampleCanvas.height = sample; const sampleContext = sampleCanvas.getContext("2d", { willReadFrequently: true }); sampleContext.drawImage(canvas, 0, 0, sample, sample); const pixels = sampleContext.getImageData(0, 0, sample, sample).data; let transparent = 0; for (let index = 3; index < pixels.length; index += 4) if (pixels[index] < 80) transparent += 1; const percentage = Math.round(transparent / (sample * sample) * 100); progressBar.style.width = `${percentage}%`; status.textContent = `${percentage}% revealed`; if (percentage >= 58) finishScratch(); }
  function erase(from, to) { context.save(); context.globalCompositeOperation = "destination-out"; context.lineCap = "round"; context.lineJoin = "round"; context.lineWidth = innerWidth < 600 ? 52 : 64; context.beginPath(); context.moveTo(from.x, from.y); context.lineTo(to.x, to.y); context.stroke(); context.restore(); updateProgress(); }
  function startScratch(event) { if (finished) return; event.preventDefault(); scratching = true; canvas.setPointerCapture?.(event.pointerId); lastPoint = point(event); erase(lastPoint, lastPoint); }
  function moveScratch(event) { if (!scratching || finished) return; event.preventDefault(); const now = performance.now(); if (typeof navigator.vibrate === "function" && now - lastVibration > 45) { navigator.vibrate(8); lastVibration = now; } const next = point(event); erase(lastPoint, next); lastPoint = next; }
  function endScratch() { scratching = false; lastPoint = null; }
  function updateCountdown() { let remaining = Math.max(0, targetDate.getTime() - Date.now()) / 1000; const values = [Math.floor(remaining / 86400)]; remaining %= 86400; values.push(Math.floor(remaining / 3600)); remaining %= 3600; values.push(Math.floor(remaining / 60), Math.floor(remaining % 60)); ["days", "hours", "minutes", "seconds"].forEach((id, index) => { const element = document.getElementById(id); if (element) element.textContent = String(values[index]).padStart(2, "0"); }); }
  function finishScratch() { if (finished) return; finished = true; scratching = false; canvas.style.transition = "opacity .8s ease"; canvas.style.opacity = "0"; card.classList.add("scratched"); countdown.classList.add("revealed"); updateCountdown(); countdownTimer = window.setInterval(updateCountdown, 1000); status.textContent = "The big day is revealed"; }
  canvas.addEventListener("pointerdown", startScratch, { passive: false }); canvas.addEventListener("pointermove", moveScratch, { passive: false }); window.addEventListener("pointerup", endScratch, { passive: true }); window.addEventListener("pointercancel", endScratch, { passive: true }); new ResizeObserver(sizeScratchCanvas).observe(card); sizeScratchCanvas();
  const decorationCount = reducedMotion ? 0 : (innerWidth < 600 ? 16 : 30); const types = ["petal", "leaf", "butterfly", "spark"];
  function createParticle(randomY) { return { type: types[Math.floor(Math.random() * types.length)], x: Math.random() * particleWidth, y: randomY ? Math.random() * particleHeight : -20, size: 5 + Math.random() * 9, speed: .25 + Math.random() * .55, drift: .2 + Math.random() * .5, opacity: .25 + Math.random() * .45, rotation: Math.random() * Math.PI * 2, rotationSpeed: (Math.random() - .5) * .02, phase: Math.random() * Math.PI * 2 }; }
  function resizeParticles() { const density = Math.min(devicePixelRatio || 1, 2); particleWidth = innerWidth; particleHeight = innerHeight; particleCanvas.width = particleWidth * density; particleCanvas.height = particleHeight * density; particleCanvas.style.width = `${particleWidth}px`; particleCanvas.style.height = `${particleHeight}px`; particleContext.setTransform(density, 0, 0, density, 0, 0); particles = Array.from({ length: decorationCount }, () => createParticle(true)); }
  function drawParticle(particle) { particleContext.save(); particleContext.translate(particle.x, particle.y); particleContext.rotate(particle.rotation); particleContext.globalAlpha = particle.opacity; if (particle.type === "petal") { particleContext.fillStyle = "#e3b6b8"; particleContext.beginPath(); particleContext.ellipse(0, 0, particle.size * .55, particle.size, 0, 0, Math.PI * 2); particleContext.fill(); } else if (particle.type === "leaf") { particleContext.fillStyle = "#9aa66f"; particleContext.beginPath(); particleContext.moveTo(0, -particle.size); particleContext.quadraticCurveTo(particle.size * 1.1, 0, 0, particle.size); particleContext.quadraticCurveTo(-particle.size * 1.1, 0, 0, -particle.size); particleContext.fill(); } else if (particle.type === "butterfly") { const flap = .55 + .45 * Math.sin(particle.phase * 2); particleContext.fillStyle = "#c79ab2"; particleContext.beginPath(); particleContext.ellipse(-particle.size * .5, 0, particle.size * flap, particle.size * .75, 0, 0, Math.PI * 2); particleContext.ellipse(particle.size * .5, 0, particle.size * flap, particle.size * .75, 0, 0, Math.PI * 2); particleContext.fill(); particleContext.fillStyle = "#4f2c3d"; particleContext.fillRect(-.8, -particle.size * .55, 1.6, particle.size * 1.1); } else { particleContext.strokeStyle = "#d8b370"; particleContext.lineWidth = .8; particleContext.beginPath(); particleContext.moveTo(-particle.size, 0); particleContext.lineTo(particle.size, 0); particleContext.moveTo(0, -particle.size); particleContext.lineTo(0, particle.size); particleContext.stroke(); } particleContext.restore(); }
  function animateParticles() { if (!particleActive || document.visibilityState === "hidden") { particleFrame = null; return; } particleContext.clearRect(0, 0, particleWidth, particleHeight); particles.forEach((particle) => { particle.phase += .03; particle.y += particle.speed; particle.x += Math.sin(particle.phase) * particle.drift; particle.rotation += particle.rotationSpeed; if (particle.y > particleHeight + 25) Object.assign(particle, createParticle(false)); drawParticle(particle); }); particleFrame = requestAnimationFrame(animateParticles); }
  function setParticleActivity(active) { particleActive = active && document.visibilityState === "visible" && !reducedMotion; if (particleActive && particleFrame === null) particleFrame = requestAnimationFrame(animateParticles); }
  const particleObserver = new IntersectionObserver(([entry]) => setParticleActivity(entry.isIntersecting), { threshold: 0 }); particleObserver.observe(particleCanvas); document.addEventListener("visibilitychange", () => setParticleActivity(particleActive)); window.addEventListener("resize", resizeParticles, { passive: true }); resizeParticles(); setParticleActivity(true);
  window.addEventListener("pagehide", () => { if (countdownTimer) clearInterval(countdownTimer); particleObserver.disconnect(); if (particleFrame !== null) cancelAnimationFrame(particleFrame); });
})();
